import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
const NAV=['Studio','Method','Archive','Journal'];
const WORK=[['01','RemedyEase','A quiet healthcare workspace designed around clarity, care, and the details that make a product feel finished.','REACT · TYPESCRIPT · API'],['02','Water / Signal','A real-time system translating water quality sensor data into a reading you can understand at a glance.','IOT · PYTHON · ML'],['03','Post Office','A secure editorial surface for writing, shaping, and managing ideas with a deliberate interface.','REACT · NODE · JWT']];
function usePointer(){const[p,setP]=useState({x:.5,y:.5});useEffect(()=>{const f=e=>setP({x:e.clientX/innerWidth,y:e.clientY/innerHeight});addEventListener('pointermove',f,{passive:true});return()=>removeEventListener('pointermove',f)},[]);return p}
function Cosmos({p}){const ref=useRef();useEffect(()=>{const c=ref.current,x=c.getContext('2d'),s=Array.from({length:230},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.3+.18,a:Math.random()*.65+.18,t:Math.random()*7,d:Math.random()*1.8+.25}));let id,w,h,d;const resize=()=>{d=Math.min(devicePixelRatio,2);w=innerWidth;h=innerHeight;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0)};resize();addEventListener('resize',resize);const draw=t=>{x.clearRect(0,0,w,h);const a=w*(.5+(p.x-.5)*.045),b=h*(.5+(p.y-.5)*.045),g=x.createRadialGradient(a,b,0,a,b,Math.max(w,h)*.54);g.addColorStop(0,'rgba(129,79,44,.29)');g.addColorStop(.48,'rgba(58,31,17,.13)');g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,w,h);s.forEach(q=>{x.beginPath();x.arc(q.x*w+(p.x-.5)*42*q.d,q.y*h+(p.y-.5)*30*q.d,q.r,0,7);x.fillStyle=`rgba(255,244,222,${q.a*(.78+Math.sin(t/900+q.t)*.22)})`;x.fill()});id=requestAnimationFrame(draw)};id=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(id);removeEventListener('resize',resize)}},[p]);return <canvas className="cosmos" ref={ref}/>}
function Hourglass({p}){const tilt=`perspective(1100px) rotateX(${(p.y-.5)*-10}deg) rotateY(${(p.x-.5)*13}deg)`;return <div className="hourglass-scene" style={{transform:tilt}}><div className="aura"/><div className="hourglass"><div className="cap cap-top"/><div className="cap cap-bottom"/><div className="glass glass-top"><div className="sand sand-top"/></div><div className="glass glass-bottom"><div className="sand-fall"/>{Array.from({length:24},(_,i)=><i className="grain-dot" style={{'--x':`${(i*37)%96}%`,'--d':`${.8+(i%7)*.16}s`}} key={i}/>)}</div><div className="waist"/><div className="glint glint-a"/><div className="glint glint-b"/></div></div>}
function App(){const p=usePointer(),[open,setOpen]=useState(false);return <main><Cosmos p={p}/><div className="grain"/><header className="nav"><a className="brand" href="#home"><span>AV</span><strong>ADITYA</strong></a><nav>{NAV.map(n=><a key={n} href={`#${n.toLowerCase()}`}>{n}</a>)}</nav><i/><a className="cta" href="#contact">Let’s talk <b>↗</b></a><button onClick={()=>setOpen(!open)}>{open?'×':'☰'}</button></header>{open&&<div className="mobile">{NAV.map(n=><a key={n} onClick={()=>setOpen(false)} href="#archive">{n}</a>)}<a href="#contact">Let’s talk ↗</a></div>}
<section className="hero" id="home"><div className="copy"><p className="eyebrow"><b>01</b> — THE LARGER CLOCK</p><h1>Building digital<br/><em>experiences</em> that move.</h1><p className="intro">Full stack developer and AI/ML engineer. I turn complex ideas into focused products, graceful interactions, and systems with a pulse.</p><div className="actions"><a className="pill" href="#archive">Explore selected work <b>↗</b></a><a className="text" href="#method">My approach →</a></div></div><Hourglass p={p}/><aside><i/><p>Thoughtful engineering is a kind of choreography: every element knows where it belongs, and when to move.</p><a href="#contact">Work with Aditya ↗</a></aside><div className="scroll">SCROLL TO DISCOVER <i/></div></section>
<section className="method" id="method"><p className="eyebrow"><b>02</b> — METHOD</p><h2>Technology should feel <em>inevitable</em>, not overwhelming.</h2><p>I work across frontend engineering, robust APIs, and applied machine learning—bringing a clear visual point of view to the systems underneath.</p></section>
<section className="archive" id="archive"><div className="head"><p className="eyebrow"><b>03</b> — ARCHIVE</p><h2>Selected signals</h2><span>HOVER TO REVEAL</span></div><div className="projects">{WORK.map(([n,t,d,k])=><article key={t}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><small>{k}</small><a href="#contact">↗</a></article>)}</div></section>
<section className="contact" id="contact"><p className="eyebrow"><b>04</b> — MAKE CONTACT</p><h2>Have a good idea?<br/><em>Let’s give it time.</em></h2><a href="mailto:hello@adityaverma.dev">hello@adityaverma.dev ↗</a><footer><span>© 2026 ADITYA VERMA</span><span>DESIGNED WITH INTENTION</span></footer></section><div className="logo">A<span>V</span></div></main>};createRoot(document.getElementById('root')).render(<App/>);
